#include "common.h"

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4E_BowserToadSwapPlacesYoshiBoard/28BC70", func_800F65E0_BowserToadSwapPlacesYoshiBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4E_BowserToadSwapPlacesYoshiBoard/28BC70", func_800F66B4_BowserToadSwapPlacesYoshiBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4E_BowserToadSwapPlacesYoshiBoard/28BC70", func_800F6708_BowserToadSwapPlacesYoshiBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4E_BowserToadSwapPlacesYoshiBoard/28BC70", func_800F67BC_BowserToadSwapPlacesYoshiBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4E_BowserToadSwapPlacesYoshiBoard/28BC70", func_800F7330_BowserToadSwapPlacesYoshiBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4E_BowserToadSwapPlacesYoshiBoard/28BC70", func_800F737C_BowserToadSwapPlacesYoshiBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4E_BowserToadSwapPlacesYoshiBoard/28BC70", func_800F73C0_BowserToadSwapPlacesYoshiBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4E_BowserToadSwapPlacesYoshiBoard/28BC70", func_800F7680_BowserToadSwapPlacesYoshiBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4E_BowserToadSwapPlacesYoshiBoard/28BC70", func_800F7764_BowserToadSwapPlacesYoshiBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4E_BowserToadSwapPlacesYoshiBoard/28BC70", func_800F7818_BowserToadSwapPlacesYoshiBoard);
