#include "common.h"

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_41_YoshisTropicalIslandEndingScene/25FC70", func_800F65E0_YoshisTropicalIslandEndingScene);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_41_YoshisTropicalIslandEndingScene/25FC70", func_800F6658_YoshisTropicalIslandEndingScene);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_41_YoshisTropicalIslandEndingScene/25FC70", func_800F671C_YoshisTropicalIslandEndingScene);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_41_YoshisTropicalIslandEndingScene/25FC70", func_800F67AC_YoshisTropicalIslandEndingScene);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_41_YoshisTropicalIslandEndingScene/25FC70", func_800F67EC_YoshisTropicalIslandEndingScene);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_41_YoshisTropicalIslandEndingScene/25FC70", func_800F697C_YoshisTropicalIslandEndingScene);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_41_YoshisTropicalIslandEndingScene/25FC70", func_800F69B8_YoshisTropicalIslandEndingScene);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_41_YoshisTropicalIslandEndingScene/25FC70", func_800F69EC_YoshisTropicalIslandEndingScene);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_41_YoshisTropicalIslandEndingScene/25FC70", func_800F6A4C_YoshisTropicalIslandEndingScene);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_41_YoshisTropicalIslandEndingScene/25FC70", func_800F6A90_YoshisTropicalIslandEndingScene);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_41_YoshisTropicalIslandEndingScene/25FC70", func_800F6B54_YoshisTropicalIslandEndingScene);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_41_YoshisTropicalIslandEndingScene/25FC70", func_800F6C80_YoshisTropicalIslandEndingScene);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_41_YoshisTropicalIslandEndingScene/25FC70", func_800F6D18_YoshisTropicalIslandEndingScene);
