#include "common.h"

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4C_PiranhaPlantStarStealPeachBoard/289BA0", func_800F65E0_PiranhaPlantStarStealPeachBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4C_PiranhaPlantStarStealPeachBoard/289BA0", func_800F66B4_PiranhaPlantStarStealPeachBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4C_PiranhaPlantStarStealPeachBoard/289BA0", func_800F6FD4_PiranhaPlantStarStealPeachBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4C_PiranhaPlantStarStealPeachBoard/289BA0", func_800F7020_PiranhaPlantStarStealPeachBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4C_PiranhaPlantStarStealPeachBoard/289BA0", func_800F7064_PiranhaPlantStarStealPeachBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4C_PiranhaPlantStarStealPeachBoard/289BA0", func_800F7120_PiranhaPlantStarStealPeachBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4C_PiranhaPlantStarStealPeachBoard/289BA0", func_800F718C_PiranhaPlantStarStealPeachBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4C_PiranhaPlantStarStealPeachBoard/289BA0", func_800F7348_PiranhaPlantStarStealPeachBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4C_PiranhaPlantStarStealPeachBoard/289BA0", func_800F741C_PiranhaPlantStarStealPeachBoard);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_4C_PiranhaPlantStarStealPeachBoard/289BA0", func_800F74C4_PiranhaPlantStarStealPeachBoard);
