#include "common.h"

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F65E0_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F66C0_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F67D0_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F6A3C_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F6AC8_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F6B0C_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F6B6C_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F6BAC_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F6BEC_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F6DCC_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F7158_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F72B0_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F75C0_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F7914_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F7A40_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F7CCC_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F7D94_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F7F0C_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F8040_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F81C0_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/303E70", func_800F8200_MinigameStadiumMinigameResultsScreen);
