#include "common.h"

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/306290", func_800F8A00_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/306290", func_800F8DB4_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/306290", func_800F8E28_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/306290", func_800F8E74_MinigameStadiumMinigameResultsScreen);

INCLUDE_ASM("asm/nonmatchings/overlays/ovl_7B_MinigameStadiumMinigameResultsScreen/306290", func_800F91CC_MinigameStadiumMinigameResultsScreen);
